import { sanitizeFileName } from '../utils/formatting';

export class ExportService {
  public static async copyToClipboard(text: string): Promise<boolean> {
    try {
      if (navigator?.clipboard?.writeText) {
        await navigator.clipboard.writeText(text);
        return true;
      }
      // Fallback
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.opacity = '0';
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      console.error('Failed to copy to clipboard', err);
      return false;
    }
  }

  public static downloadTxt(title: string, content: string, suffix: string = 'summary'): void {
    const filename = `${sanitizeFileName(title)}_${suffix}.txt`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  public static downloadMarkdown(
    title: string,
    summary: string,
    paragraph?: string,
    metadata?: {
      sourceWords?: number;
      summaryWords?: number;
      compressionRatio?: number;
      mode?: string;
    }
  ): void {
    const filename = `${sanitizeFileName(title)}_summary.md`;
    let md = `# ${title}\n\n`;
    md += `*Generated by LocalSummarize AI (Private On-Device Model)*\n\n`;

    if (metadata) {
      md += `### Metadata\n`;
      if (metadata.mode) md += `- **Summary Mode**: ${metadata.mode}\n`;
      if (metadata.sourceWords) md += `- **Source Words**: ${metadata.sourceWords}\n`;
      if (metadata.summaryWords) md += `- **Summary Words**: ${metadata.summaryWords}\n`;
      if (metadata.compressionRatio)
        md += `- **Compression Ratio**: ${(metadata.compressionRatio * 100).toFixed(1)}%\n`;
      md += `\n---\n\n`;
    }

    md += `## Structured Summary\n\n${summary}\n\n`;

    if (paragraph && paragraph.trim().length > 0) {
      md += `## Cohesive Paragraph Version\n\n${paragraph}\n\n`;
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  public static printSummary(title: string, summary: string, paragraph?: string): void {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - LocalSummarize AI</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              padding: 40px;
              color: #0f172a;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 { font-size: 24px; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
            h2 { font-size: 18px; color: #2563eb; margin-top: 24px; }
            p { font-size: 15px; margin-bottom: 16px; white-space: pre-wrap; }
            .badge {
              display: inline-block;
              padding: 4px 10px;
              background: #f1f5f9;
              border-radius: 12px;
              font-size: 12px;
              color: #475569;
              margin-bottom: 20px;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="badge">LocalSummarize AI • On-Device Summary</div>
          <h2>Structured Summary</h2>
          <p>${summary}</p>
          ${paragraph ? `<h2>Paragraph Version</h2><p>${paragraph}</p>` : ''}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}
