import { sanitizeFileName } from '../utils/formatting';
import jsPDF from 'jspdf';

/**
 * Strips unprintable emojis and markdown to prevent WinAnsiEncoding or sizing exceptions in jsPDF
 */
export function cleanTextForPdf(text: string): string {
  if (!text) return '';
  return text
    // Replace markdown headers
    .replace(/^#{1,6}\s+/gm, '')
    // Replace markdown bold/italic
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/__(.*?)__/g, '$1')
    .replace(/_(.*?)_/g, '$1')
    // Replace emojis with clean textual indicators
    .replace(/🎯/g, '[Core Claim]')
    .replace(/📌/g, '[Key Point]')
    .replace(/📊/g, '[Data & Facts]')
    .replace(/💡/g, '[Takeaway]')
    .replace(/⚡/g, '[Highlight]')
    .replace(/🧠/g, '[Analysis]')
    .replace(/🔍/g, '[Detail]')
    .replace(/⚠️/g, '[Notice]')
    .replace(/❓/g, '[Question]')
    .replace(/✨/g, '*')
    // Standardize unicode bullets to clean ASCII hyphen bullets
    .replace(/[•●▪]/g, '- ')
    // Standardize quotes and hyphens
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    // Strip other unicode emojis outside standard latin-1 range to guarantee jsPDF compatibility
    .replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '')
    .replace(/[^\x00-\x7F\xA0-\xFF]/g, ' ');
}

/**
 * Formats text cleanly for Plain Text (.txt) files and Microsoft Word / Notepad opening.
 * - Strips raw markdown syntax (###, **)
 * - Converts emojis to readable section titles/tags [Core Claim], [Key Points], [Takeaway]
 * - Converts unicode bullets (•) to clean ASCII dashes (- ) to prevent Windows GBK / SimSun mis-encoding
 * - Uses CRLF (\r\n) line breaks for Windows Notepad / Word compatibility
 */
export function cleanTextForTxt(title: string, content: string): string {
  if (!content) return '';

  const cleaned = content
    // Replace markdown headers (### Header) with clean section dividers
    .replace(/^#{1,6}\s*(.*)$/gm, '\r\n--- $1 ---\r\n')
    // Strip markdown bold and italic asterisks
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/__(.*?)__/g, '$1')
    .replace(/_(.*?)_/g, '$1')
    // Replace emojis with clean ASCII textual tags
    .replace(/🎯/g, '[Core Claim]')
    .replace(/📌/g, '[Key Point]')
    .replace(/📊/g, '[Data & Facts]')
    .replace(/💡/g, '[Takeaway]')
    .replace(/⚡/g, '[Highlight]')
    .replace(/🧠/g, '[Analysis]')
    .replace(/🔍/g, '[Detail]')
    .replace(/⚠️/g, '[Notice]')
    .replace(/❓/g, '[Question]')
    .replace(/✨/g, '*')
    // Standardize bullets to standard ASCII hyphen bullet so no SimSun encoding triggers
    .replace(/[•●▪]/g, '- ')
    // Standardize quotes and hyphens to ASCII
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    // Strip any remaining high-surrogate emojis
    .replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '')
    // Normalize newlines to Windows CRLF for Notepad and Word
    .replace(/\r?\n/g, '\r\n')
    .trim();

  const safeTitle = (title || 'Document Summary')
    .replace(/[•●▪🎯📌💡⚡🧠🔍⚠️❓✨]/g, '')
    .replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '')
    .trim();

  const border = '================================================================';
  const header = [
    border,
    `JAVERIA AI - DOCUMENT SUMMARY REPORT`,
    `Subject:   ${safeTitle}`,
    `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}`,
    border,
    '',
    '',
  ].join('\r\n');

  const footer = [
    '',
    '',
    border,
    `Report generated by Javeria AI Platform (100% On-Device Engine)`,
    border,
  ].join('\r\n');

  return header + cleaned + footer;
}

export class ExportService {
  private static triggerDownload(doc: jsPDF, filename: string): string | null {
    try {
      const blob = doc.output('blob');
      const blobUrl = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = blobUrl;
      link.download = filename;
      link.target = '_blank';
      link.rel = 'noopener noreferrer';
      document.body.appendChild(link);
      link.click();
      setTimeout(() => {
        document.body.removeChild(link);
        // Keep blob alive for a short while so fallback links work
        setTimeout(() => URL.revokeObjectURL(blobUrl), 60000);
      }, 1500);
      return blobUrl;
    } catch (blobErr) {
      console.warn('Blob URL download failed, falling back to doc.save:', blobErr);
      try {
        doc.save(filename);
      } catch (saveErr) {
        console.error('doc.save failed:', saveErr);
      }
      return null;
    }
  }

  public static async copyToClipboard(text: string): Promise<boolean> {
    try {
      if (navigator?.clipboard?.writeText) {
        await navigator.clipboard.writeText(text);
        return true;
      }
      // Fallback
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.opacity = '0';
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      console.error('Failed to copy to clipboard', err);
      return false;
    }
  }

  public static downloadTxt(title: string, content: string, suffix: string = 'summary'): void {
    const rawSafe = sanitizeFileName(title) || 'javeria_ai_document';
    const filename = `${rawSafe}_${suffix}.txt`;
    const formatted = cleanTextForTxt(title, content);
    // Crucial: \uFEFF Byte Order Mark guarantees Windows Word, Notepad, etc. recognize UTF-8
    // and never misinterpret emojis/bullets as Chinese SimSun (GBK)
    const blob = new Blob(['\uFEFF' + formatted], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 1500);
  }

  /**
   * Generates a Microsoft Word (.doc) document that opens natively with rich typography
   */
  public static downloadDoc(title: string, content: string, suffix: string = 'summary'): void {
    const rawSafe = sanitizeFileName(title) || 'javeria_ai_document';
    const filename = `${rawSafe}_${suffix}.doc`;

    const cleanTitle = (title || 'Document Summary')
      .replace(/[•●▪🎯📌💡⚡🧠🔍⚠️❓✨]/g, '')
      .replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '')
      .trim();

    const cleanBody = content
      .replace(/^#{1,6}\s*(.*)$/gm, '<h3 style="color:#1d4ed8;margin-top:16px;margin-bottom:6px;font-size:13pt;">$1</h3>')
      .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')
      .replace(/\*(.*?)\*/g, '<i>$1</i>')
      .replace(/🎯/g, '[Core Claim]')
      .replace(/📌/g, '[Key Point]')
      .replace(/📊/g, '[Data]')
      .replace(/💡/g, '[Takeaway]')
      .replace(/^[•●▪\-]\s*(.*)$/gm, '<li style="margin-bottom:4px;">$1</li>')
      .replace(/\n\n/g, '<p></p>')
      .replace(/\n/g, '<br/>');

    const html = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${cleanTitle}</title>
        <style>
          body { font-family: 'Segoe UI', Calibri, Arial, sans-serif; font-size: 11pt; color: #1e293b; line-height: 1.6; padding: 24px; }
          h1 { color: #1e40af; font-size: 18pt; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 8px; }
          h3 { color: #2563eb; font-size: 13pt; margin-top: 18px; margin-bottom: 6px; }
          .meta { color: #64748b; font-size: 9.5pt; margin-bottom: 18px; }
          ul, ol { margin-top: 6px; margin-bottom: 12px; }
          li { margin-bottom: 4px; }
          .footer { margin-top: 32px; font-size: 9pt; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 8px; }
        </style>
      </head>
      <body>
        <h1>${cleanTitle}</h1>
        <div class="meta">Report Generated by Javeria AI Platform &bull; ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}</div>
        <div>${cleanBody}</div>
        <div class="footer">Javeria AI Platform &bull; 100% On-Device Local Engine &bull; Confidential</div>
      </body>
      </html>
    `;

    const blob = new Blob(['\uFEFF' + html], { type: 'application/msword;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 1500);
  }

  public static downloadMarkdown(
    title: string,
    summary: string,
    paragraph?: string,
    metadata?: {
      sourceWords?: number;
      summaryWords?: number;
      compressionRatio?: number;
      mode?: string;
    }
  ): void {
    const rawSafe = sanitizeFileName(title) || 'javeria_ai_document';
    const filename = `${rawSafe}_summary.md`;
    let md = `# ${title}\n\n`;
    md += `*Generated by Javeria AI Platform*\n\n`;

    if (metadata) {
      md += `### Metadata\n`;
      if (metadata.mode) md += `- **Summary Mode**: ${metadata.mode}\n`;
      if (metadata.sourceWords) md += `- **Source Words**: ${metadata.sourceWords}\n`;
      if (metadata.summaryWords) md += `- **Summary Words**: ${metadata.summaryWords}\n`;
      if (metadata.compressionRatio)
        md += `- **Compression Ratio**: ${(metadata.compressionRatio * 100).toFixed(1)}%\n`;
      md += `\n---\n\n`;
    }

    md += `## Structured Summary\n\n${summary}\n\n`;

    if (paragraph && paragraph.trim().length > 0) {
      md += `## Cohesive Paragraph Version\n\n${paragraph}\n\n`;
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 1500);
  }

  /**
   * Generates a professionally styled PDF document containing Summary and/or Paragraph
   */
  public static downloadPdf(
    title: string,
    summary: string,
    paragraph?: string,
    metadata?: {
      sourceWords?: number;
      summaryWords?: number;
      compressionRatio?: number;
      mode?: string;
    }
  ): string | null {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 18;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    // Helper: Add page break if needed
    const ensureSpace = (neededHeight: number) => {
      if (y + neededHeight > pageHeight - margin) {
        doc.addPage();
        y = margin + 8;
      }
    };

    const cleanTitle = cleanTextForPdf(title || 'Document Summary');
    const cleanSummary = cleanTextForPdf(summary || '');
    const cleanParagraph = cleanTextForPdf(paragraph || '');

    // --- Header Branding ---
    doc.setFillColor(37, 99, 235); // Royal blue accent
    doc.rect(margin, y, 4, 14, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text('Javeria AI Document Report', margin + 8, y + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(
      `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}`,
      margin + 8,
      y + 12
    );

    y += 22;

    // --- Document Title Banner ---
    doc.setFillColor(248, 250, 252); // slate-50
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.roundedRect(margin, y, contentWidth, 16, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    const safeTitle = cleanTitle.length > 65 ? cleanTitle.substring(0, 62) + '...' : cleanTitle;
    doc.text(`Subject: ${safeTitle}`, margin + 5, y + 10);

    y += 22;

    // --- Metadata Pill Badges (if provided) ---
    if (metadata) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);

      const metaParts: string[] = [];
      if (metadata.mode) metaParts.push(`Mode: ${metadata.mode}`);
      if (metadata.sourceWords) metaParts.push(`Original: ${metadata.sourceWords.toLocaleString()} words`);
      if (metadata.summaryWords) metaParts.push(`Summary: ${metadata.summaryWords.toLocaleString()} words`);
      if (metadata.compressionRatio) {
        metaParts.push(`Compression: ${(metadata.compressionRatio * 100).toFixed(0)}%`);
      }

      if (metaParts.length > 0) {
        doc.text(metaParts.join('   •   '), margin, y);
        y += 7;
        doc.setDrawColor(241, 245, 249);
        doc.line(margin, y, margin + contentWidth, y);
        y += 8;
      }
    }

    // --- Section: Structured Summary ---
    if (cleanSummary && cleanSummary.trim().length > 0) {
      ensureSpace(20);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(37, 99, 235); // Blue
      doc.text('Key Summary & Highlights', margin, y);
      y += 7;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85); // Slate 700

      const splitSummary = doc.splitTextToSize(cleanSummary, contentWidth);
      for (const line of splitSummary) {
        ensureSpace(6);
        doc.text(line, margin, y);
        y += 5.2;
      }

      y += 8;
    }

    // --- Section: Flowing Paragraph Synthesis ---
    if (cleanParagraph && cleanParagraph.trim().length > 0) {
      ensureSpace(25);

      doc.setDrawColor(226, 232, 240);
      doc.line(margin, y, margin + contentWidth, y);
      y += 9;

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(99, 102, 241); // Indigo
      doc.text('Flowing Paragraph Synthesis', margin, y);
      y += 7;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);

      const splitPara = doc.splitTextToSize(cleanParagraph, contentWidth);
      for (const line of splitPara) {
        ensureSpace(6);
        doc.text(line, margin, y);
        y += 5.2;
      }
    }

    // --- Footer page numbers on all pages ---
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // Slate 400
      doc.text(
        `Javeria AI Platform • Confidential Document • Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
    }

    const rawSafe = sanitizeFileName(cleanTitle) || 'javeria_ai_summary';
    const filename = `${rawSafe}_summary.pdf`;
    return this.triggerDownload(doc, filename);
  }

  /**
   * Download single active text (either summary or paragraph) as a standalone PDF
   */
  public static downloadSingleTextPdf(
    title: string,
    content: string,
    typeLabel: 'Summary' | 'Paragraph' | 'Document' = 'Summary'
  ): string | null {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 18;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    const ensureSpace = (neededHeight: number) => {
      if (y + neededHeight > pageHeight - margin) {
        doc.addPage();
        y = margin + 8;
      }
    };

    const cleanTitle = cleanTextForPdf(title || `${typeLabel} Document`);
    const cleanContent = cleanTextForPdf(content || '');

    // Branding header
    doc.setFillColor(37, 99, 235);
    doc.rect(margin, y, 4, 12, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Javeria AI • ${typeLabel}`, margin + 7, y + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Document: ${cleanTitle.length > 55 ? cleanTitle.substring(0, 52) + '...' : cleanTitle}  •  ${new Date().toLocaleDateString()}`,
      margin + 7,
      y + 11
    );

    y += 20;

    // Body content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);

    const splitContent = doc.splitTextToSize(cleanContent, contentWidth);
    for (const line of splitContent) {
      ensureSpace(6);
      doc.text(line, margin, y);
      y += 5.2;
    }

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Javeria AI • ${typeLabel} • Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
    }

    const rawSafe = sanitizeFileName(cleanTitle) || 'javeria_ai_doc';
    const filename = `${rawSafe}_${typeLabel.toLowerCase()}.pdf`;
    return this.triggerDownload(doc, filename);
  }

  public static printSummary(title: string, summary: string, paragraph?: string): void {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - Javeria AI</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              padding: 40px;
              color: #0f172a;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 { font-size: 24px; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
            h2 { font-size: 18px; color: #2563eb; margin-top: 24px; }
            p { font-size: 15px; margin-bottom: 16px; white-space: pre-wrap; }
            .badge {
              display: inline-block;
              padding: 4px 10px;
              background: #f1f5f9;
              border-radius: 12px;
              font-size: 12px;
              color: #475569;
              margin-bottom: 20px;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="badge">Javeria AI • Document Report</div>
          <h2>Structured Summary</h2>
          <p>${summary}</p>
          ${paragraph ? `<h2>Paragraph Version</h2><p>${paragraph}</p>` : ''}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}
