import { sanitizeFileName } from '../utils/formatting';
import jsPDF from 'jspdf';

export class ExportService {
  public static async copyToClipboard(text: string): Promise<boolean> {
    try {
      if (navigator?.clipboard?.writeText) {
        await navigator.clipboard.writeText(text);
        return true;
      }
      // Fallback
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.opacity = '0';
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      console.error('Failed to copy to clipboard', err);
      return false;
    }
  }

  public static downloadTxt(title: string, content: string, suffix: string = 'summary'): void {
    const filename = `${sanitizeFileName(title)}_${suffix}.txt`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  public static downloadMarkdown(
    title: string,
    summary: string,
    paragraph?: string,
    metadata?: {
      sourceWords?: number;
      summaryWords?: number;
      compressionRatio?: number;
      mode?: string;
    }
  ): void {
    const filename = `${sanitizeFileName(title)}_summary.md`;
    let md = `# ${title}\n\n`;
    md += `*Generated by Javeria AI Platform*\n\n`;

    if (metadata) {
      md += `### Metadata\n`;
      if (metadata.mode) md += `- **Summary Mode**: ${metadata.mode}\n`;
      if (metadata.sourceWords) md += `- **Source Words**: ${metadata.sourceWords}\n`;
      if (metadata.summaryWords) md += `- **Summary Words**: ${metadata.summaryWords}\n`;
      if (metadata.compressionRatio)
        md += `- **Compression Ratio**: ${(metadata.compressionRatio * 100).toFixed(1)}%\n`;
      md += `\n---\n\n`;
    }

    md += `## Structured Summary\n\n${summary}\n\n`;

    if (paragraph && paragraph.trim().length > 0) {
      md += `## Cohesive Paragraph Version\n\n${paragraph}\n\n`;
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Generates a professionally styled PDF document containing Summary and/or Paragraph
   */
  public static downloadPdf(
    title: string,
    summary: string,
    paragraph?: string,
    metadata?: {
      sourceWords?: number;
      summaryWords?: number;
      compressionRatio?: number;
      mode?: string;
    }
  ): void {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 18;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    // Helper: Add page break if needed
    const ensureSpace = (neededHeight: number) => {
      if (y + neededHeight > pageHeight - margin) {
        doc.addPage();
        y = margin + 8;
      }
    };

    // --- Header Branding ---
    doc.setFillColor(37, 99, 235); // Royal blue accent
    doc.rect(margin, y, 4, 14, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text('Javeria AI Document Report', margin + 8, y + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(
      `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}`,
      margin + 8,
      y + 12
    );

    y += 22;

    // --- Document Title Banner ---
    doc.setFillColor(248, 250, 252); // slate-50
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.roundedRect(margin, y, contentWidth, 16, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    const safeTitle = title.length > 65 ? title.substring(0, 62) + '...' : title;
    doc.text(`Subject: ${safeTitle}`, margin + 5, y + 10);

    y += 22;

    // --- Metadata Pill Badges (if provided) ---
    if (metadata) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);

      const metaParts: string[] = [];
      if (metadata.mode) metaParts.push(`Mode: ${metadata.mode}`);
      if (metadata.sourceWords) metaParts.push(`Original: ${metadata.sourceWords.toLocaleString()} words`);
      if (metadata.summaryWords) metaParts.push(`Summary: ${metadata.summaryWords.toLocaleString()} words`);
      if (metadata.compressionRatio) {
        metaParts.push(`Compression: ${(metadata.compressionRatio * 100).toFixed(0)}%`);
      }

      if (metaParts.length > 0) {
        doc.text(metaParts.join('   •   '), margin, y);
        y += 7;
        doc.setDrawColor(241, 245, 249);
        doc.line(margin, y, margin + contentWidth, y);
        y += 8;
      }
    }

    // --- Section: Structured Summary ---
    if (summary && summary.trim().length > 0) {
      ensureSpace(20);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(37, 99, 235); // Blue
      doc.text('Key Summary & Highlights', margin, y);
      y += 7;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85); // Slate 700

      const splitSummary = doc.splitTextToSize(summary, contentWidth);
      for (const line of splitSummary) {
        ensureSpace(6);
        doc.text(line, margin, y);
        y += 5.2;
      }

      y += 8;
    }

    // --- Section: Flowing Paragraph Synthesis ---
    if (paragraph && paragraph.trim().length > 0) {
      ensureSpace(25);

      doc.setDrawColor(226, 232, 240);
      doc.line(margin, y, margin + contentWidth, y);
      y += 9;

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(99, 102, 241); // Indigo
      doc.text('Flowing Paragraph Synthesis', margin, y);
      y += 7;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);

      const splitPara = doc.splitTextToSize(paragraph, contentWidth);
      for (const line of splitPara) {
        ensureSpace(6);
        doc.text(line, margin, y);
        y += 5.2;
      }
    }

    // --- Footer page numbers on all pages ---
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // Slate 400
      doc.text(
        `Javeria AI Platform • Confidential Document • Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
    }

    const filename = `${sanitizeFileName(title)}_summary.pdf`;
    doc.save(filename);
  }

  /**
   * Download single active text (either summary or paragraph) as a standalone PDF
   */
  public static downloadSingleTextPdf(
    title: string,
    content: string,
    typeLabel: 'Summary' | 'Paragraph' | 'Document' = 'Summary'
  ): void {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 18;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    const ensureSpace = (neededHeight: number) => {
      if (y + neededHeight > pageHeight - margin) {
        doc.addPage();
        y = margin + 8;
      }
    };

    // Branding header
    doc.setFillColor(37, 99, 235);
    doc.rect(margin, y, 4, 12, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Javeria AI • ${typeLabel}`, margin + 7, y + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Document: ${title.length > 55 ? title.substring(0, 52) + '...' : title}  •  ${new Date().toLocaleDateString()}`,
      margin + 7,
      y + 11
    );

    y += 20;

    // Body content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);

    const splitContent = doc.splitTextToSize(content, contentWidth);
    for (const line of splitContent) {
      ensureSpace(6);
      doc.text(line, margin, y);
      y += 5.2;
    }

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Javeria AI • ${typeLabel} • Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
    }

    const filename = `${sanitizeFileName(title)}_${typeLabel.toLowerCase()}.pdf`;
    doc.save(filename);
  }

  public static printSummary(title: string, summary: string, paragraph?: string): void {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - Javeria AI</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              padding: 40px;
              color: #0f172a;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
            }
            h1 { font-size: 24px; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
            h2 { font-size: 18px; color: #2563eb; margin-top: 24px; }
            p { font-size: 15px; margin-bottom: 16px; white-space: pre-wrap; }
            .badge {
              display: inline-block;
              padding: 4px 10px;
              background: #f1f5f9;
              border-radius: 12px;
              font-size: 12px;
              color: #475569;
              margin-bottom: 20px;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="badge">Javeria AI • Document Report</div>
          <h2>Structured Summary</h2>
          <p>${summary}</p>
          ${paragraph ? `<h2>Paragraph Version</h2><p>${paragraph}</p>` : ''}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}
