import React from 'react';
import { X, FileText, Sparkles, TrendingUp, BookOpen, Scale, Check } from 'lucide-react';
import { SummaryMode } from '../types';

interface TemplatesModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectTemplate: (title: string, content: string, mode: SummaryMode) => void;
}

const TEMPLATES: {
  id: string;
  title: string;
  category: string;
  mode: SummaryMode;
  description: string;
  icon: React.ReactNode;
  sampleText: string;
}[] = [
  {
    id: 'research',
    title: 'Scientific & Academic Research Paper',
    category: 'Research',
    mode: 'academic',
    description: 'Structure complex methodologies, statistical findings, and conclusions.',
    icon: <BookOpen className="w-5 h-5 text-blue-500" />,
    sampleText: `Abstract—Quantum machine learning (QML) investigates the synergy between quantum computing and machine learning paradigms.
1. Introduction
With the advent of Noisy Intermediate-Scale Quantum (NISQ) devices, variational quantum algorithms (VQAs) have garnered substantial attention. Parameterized quantum circuits (PQCs) serve as quantum analogs to classical neural networks. This investigation systematically benchmarks sample complexity, gradient barren plateaus, and trainability in multi-qubit topologies across 500+ experimental circuit iterations.

2. Mathematical Formulation
Let |ψ(θ)⟩ = U(θ)|0⟩ denote the trial state generated by ansatz U(θ). The cost function C(θ) = ⟨ψ(θ)|H|ψ(θ)⟩ is evaluated via quantum state tomography. Under Haar-distributed random circuits, Var[∂θ C(θ)] decays exponentially as O(2^-n), inducing barren plateaus that severely impede optimization via classical gradient descent.

3. Empirical Results & Discussion
Our empirical evaluations demonstrate that layer-by-layer pre-training and entanglement-restricted ansatz architectures retain a non-vanishing variance across n=24 qubits, reducing training epochs by 68.4%. The validation loss converged at 0.042 with a 99.2% fidelity score.`,
  },
  {
    id: 'executive_financial',
    title: 'Financial Quarterly Earnings & Spending',
    category: 'Finance',
    mode: 'executive',
    description: 'Summarize revenue streams, expenditures, EBITDA, and guidance.',
    icon: <TrendingUp className="w-5 h-5 text-emerald-500" />,
    sampleText: `Q3 FY2026 Executive Financial Briefing & Strategic Budget
1. Financial Overview
Consolidated revenue for the quarter reached $14.8 billion, representing a 22.4% year-over-year increase driven by enterprise cloud solutions and AI infrastructure subscriptions. Operating income stood at $4.2 billion, yielding an operating margin of 28.3%.

2. Capital Expenditures & Spending Allocation
R&D expenditure was $2.6 billion, focused heavily on next-generation silicon, liquid-cooled data centers, and multi-modal edge AI models. Free cash flow surged to $3.9 billion.

3. Forward Guidance & Outlook
For Q4 FY2026, projected revenues range between $15.5B and $16.1B with expected gross margins maintaining at 64.5%. Key strategic focus: scaling sovereign enterprise deployments and optimizing infrastructure cost per token by 35%.`,
  },
  {
    id: 'legal_agreement',
    title: 'Legal Contract & Terms Review',
    category: 'Legal',
    mode: 'detailed',
    description: 'Extract liabilities, confidentiality terms, and operational obligations.',
    icon: <Scale className="w-5 h-5 text-amber-500" />,
    sampleText: `MASTER SERVICES AGREEMENT (MSA) — PRIVACY & PROCESSING
This Master Services Agreement ("Agreement") governs the rights, warranties, and obligations of the Parties regarding automated information analysis.
1. Data Ownership & Protection
The Client retains all right, title, and interest in and to any proprietary documents, source text, and derivatives submitted for processing. The Provider warrants that all computational analyses are executed locally within the client's sandboxed environment without external telemetry or third-party replication.
2. Indemnification & Limitation of Liability
Neither party shall be liable for indirect, incidental, or consequential damages. Maximum aggregate liability under this Agreement is expressly limited to fees paid in the preceding twelve (12) calendar months.`,
  },
];

export const TemplatesModal: React.FC<TemplatesModalProps> = ({
  isOpen,
  onClose,
  onSelectTemplate,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in">
      <div className="w-full max-w-2xl bg-white dark:bg-[#121620] border border-slate-200 dark:border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="p-5 border-b border-slate-100 dark:border-white/5 flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-slate-900 dark:text-white">
              Prompt & Document Templates
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Select a specialized template with tuned model settings
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* List of Templates */}
        <div className="p-5 space-y-3 overflow-y-auto scrollbar-thin">
          {TEMPLATES.map((tmpl) => (
            <div
              key={tmpl.id}
              onClick={() => {
                onSelectTemplate(tmpl.title, tmpl.sampleText, tmpl.mode);
                onClose();
              }}
              className="p-4 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200/80 dark:border-white/5 hover:border-blue-500/50 cursor-pointer transition-all hover:scale-[1.01] flex items-start gap-4 group"
            >
              <div className="p-2.5 rounded-xl bg-white dark:bg-slate-800 shadow-xs shrink-0">
                {tmpl.icon}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-white group-hover:text-blue-500 transition-colors">
                    {tmpl.title}
                  </h3>
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-blue-100 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 font-medium">
                    {tmpl.category}
                  </span>
                </div>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">
                  {tmpl.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
